### ISSUE TITLE
Not working and gives constant errors with the most basic of commands 

### ISSUE THREAD

**Issue by rishabtandon03** [ChrisStevens/garc#2]
Even the most basic commands art working and give the following results , both on Mac and Linux machines.

$ garc search maga

line 11, in <module>
    load_entry_point('garc==2.0', 'console_scripts', 'garc')()
line 118, in main
    for thing in things:
 line 84, in search
    max_id = posts[-1]['id']
KeyError: -1

-RT
13/06/2020

**Comment by ChrisStevens** [comment]
@rishabtandon03 I think the issue is coming from poor error catching with respect to account login. So you have configured garc with incorrect account info.

To fix rerun:
garc configure

and make sure the username and password you give are for a valid Gab account. Then everything should work.

Please let me know if that doesn't solve the issue.

**Comment by rishabtandon03** [comment]
ooh my bad just realised!

thanks for the swift reply 
and sorry for the trouble :)
